#!/usr/bin/env python3
"""Now-playing widget for the Control Center music panel (phase 8b).

A plain GTK window whose Wayland app_id is `cc-music`, so the phase-6 window
rule in hyprland.lua floats it at the panel's fixed size/position on ws 10 —
the same phase-6 -> phase-8 contract as the other panels, no rule edits.

Data spine is `playerctl` (MPRIS), NOT the Spotify API: the widget prefers a
running Spotify client but works against any MPRIS player, so the whole
mechanism is testable in the VM with Firefox playing something (settled
decision 4 in the phase-8 spec). It shows the current track (title / artist /
album art) with previous / play-pause / next buttons. The "queue of next 2
songs" is deliberately dropped for this first cut (open decision 2, settled
with Sergi): MPRIS exposes only the current track, and the queue would need
Spotify Web API OAuth — revisit later if wanted.

Colours come from theme/colors.env (generated by theme/gen.py from the active
palette) — same runtime-read pattern as waybar/scripts/volume-slider.py, so
no hardcoded hex. The widget reads the palette once at launch; set-theme
respawns the ws-0 panels, which is what re-themes it. GTK renders via cairo
(software), so it works inside the VM.
"""
import hashlib
import os
import subprocess
import threading
import urllib.request

import gi

gi.require_version("Gtk", "3.0")
from gi.repository import GLib

# Under Wayland GTK3 takes the surface's app_id from the prgname — set it
# BEFORE any window exists so the cc-music rule matches. Same "verify the
# class on first launch" caveat as phases 4/6: python-gobject was missing in
# the VM when this was written, so check `hyprctl clients` once it runs and
# repoint the rule's match if the class isn't cc-music.
GLib.set_prgname("cc-music")

from gi.repository import Gtk, Gdk, GdkPixbuf, Pango  # noqa: E402

# Prefer the real Spotify client whenever it's running, else any MPRIS player
# (Firefox in the VM) — deliberately player-agnostic.
PLAYERCTL = ["playerctl", "--player=spotify,%any"]
POLL_MS = 1000
ART_SIZE = 110           # album-art square, px
FONT = "JetBrainsMono Nerd Font"   # the rice's bar/terminal font

# Nerd Font glyphs from the Font Awesome block (F000–F2FF survived the v3
# remap — the volume widgets already rely on 0xF028 from the same block).
# Written as \u escapes, not literals: PUA glyphs are invisible in editors
# and get silently mangled in transit (see the waybar icon memory).
ICON_PREV = "\uf048"   # nf-fa-step_backward
ICON_PLAY = "\uf04b"   # nf-fa-play
ICON_PAUSE = "\uf04c"  # nf-fa-pause
ICON_NEXT = "\uf051"   # nf-fa-step_forward
ICON_NOTE = "\uf001"   # nf-fa-music — shown while there is no album art


def load_colors():
    """Read theme/colors.env (KEY='#hex', written by theme/gen.py) into a dict."""
    config = os.environ.get("XDG_CONFIG_HOME") or os.path.expanduser("~/.config")
    colors = {}
    with open(os.path.join(config, "theme", "colors.env")) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            colors[key.strip()] = value.strip().strip("'\"")
    return colors


_C = load_colors()
BG = _C["BACKGROUND"]
ACCENT = _C["ACCENT"]
ACCENT_BRIGHT = _C["ACCENT_BRIGHT"]
MUTED = _C["MUTED"]
FOREGROUND = _C["FOREGROUND"]

CSS = f"""
window {{ background-color: {BG}; font-family: "{FONT}"; }}
#title {{ color: {ACCENT}; font-weight: bold; font-size: 15px; }}
#title.idle {{ color: {MUTED}; font-weight: normal; }}
#artist {{ color: {FOREGROUND}; font-size: 12px; }}
#art-placeholder {{ color: {MUTED}; font-size: 42px; }}
button {{
    background: none;
    border: none;
    box-shadow: none;
    color: {ACCENT};
    font-size: 20px;
    padding: 2px 16px;
}}
button:hover {{ color: {ACCENT_BRIGHT}; }}
""".encode()


def now_playing():
    """Current track via playerctl, or None when no MPRIS player is up."""
    try:
        out = subprocess.check_output(
            PLAYERCTL + ["metadata", "--format",
                         "{{status}}\t{{title}}\t{{artist}}\t{{mpris:artUrl}}"],
            stderr=subprocess.DEVNULL, timeout=2,
        ).decode()
    except Exception:
        return None
    # Pad so a track with empty fields still unpacks.
    status, title, artist, art = (out.rstrip("\n") + "\t\t\t").split("\t")[:4]
    return {"status": status, "title": title, "artist": artist, "art": art}


class MusicPanel(Gtk.Window):
    def __init__(self):
        super().__init__()
        self.set_decorated(False)  # a panel, not an app window — no CSD bar
        self.set_default_size(440, 240)
        self._art_url = None       # currently displayed art, to skip refetches

        outer = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=10)
        for side in ("top", "bottom", "start", "end"):
            getattr(outer, f"set_margin_{side}")(14)
        self.add(outer)

        # ── top: album art | title / artist ─────────────────────────────
        row = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=14)
        outer.pack_start(row, True, True, 0)

        self.art_stack = Gtk.Stack()
        self.art_image = Gtk.Image()
        note = Gtk.Label(label=ICON_NOTE)
        note.set_name("art-placeholder")
        self.art_stack.add_named(note, "placeholder")
        self.art_stack.add_named(self.art_image, "art")
        self.art_stack.set_size_request(ART_SIZE, ART_SIZE)
        row.pack_start(self.art_stack, False, False, 0)

        text = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=4)
        text.set_valign(Gtk.Align.CENTER)
        row.pack_start(text, True, True, 0)

        self.title = Gtk.Label(xalign=0)
        self.title.set_name("title")
        self.title.set_ellipsize(Pango.EllipsizeMode.END)
        text.pack_start(self.title, False, False, 0)

        self.artist = Gtk.Label(xalign=0)
        self.artist.set_name("artist")
        self.artist.set_ellipsize(Pango.EllipsizeMode.END)
        text.pack_start(self.artist, False, False, 0)

        # ── bottom: previous / play-pause / next ────────────────────────
        controls = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=6)
        controls.set_halign(Gtk.Align.CENTER)
        outer.pack_start(controls, False, False, 0)

        self.play_btn = None
        for icon, verb in ((ICON_PREV, "previous"),
                           (ICON_PLAY, "play-pause"),
                           (ICON_NEXT, "next")):
            btn = Gtk.Button(label=icon)
            btn.set_relief(Gtk.ReliefStyle.NONE)
            btn.connect("clicked", self._on_control, verb)
            controls.pack_start(btn, False, False, 0)
            if verb == "play-pause":
                self.play_btn = btn

        self._apply_css()
        self._refresh()
        GLib.timeout_add(POLL_MS, self._refresh)

    def _apply_css(self):
        provider = Gtk.CssProvider()
        provider.load_from_data(CSS)
        Gtk.StyleContext.add_provider_for_screen(
            Gdk.Screen.get_default(),
            provider,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION,
        )

    def _on_control(self, _btn, verb):
        subprocess.Popen(PLAYERCTL + [verb],
                         stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        # Poll right after so the play/pause icon flips without the 1 s lag.
        GLib.timeout_add(150, lambda: self._refresh() and False)

    def _refresh(self):
        track = now_playing()
        if track is None or not (track["title"] or track["artist"]):
            self.title.set_text("nothing playing")
            self.title.get_style_context().add_class("idle")
            self.artist.set_text("")
            self.play_btn.set_label(ICON_PLAY)
            self._show_art(None)
            return True

        self.title.set_text(track["title"] or "—")
        self.title.get_style_context().remove_class("idle")
        self.artist.set_text(track["artist"])
        self.play_btn.set_label(
            ICON_PAUSE if track["status"] == "Playing" else ICON_PLAY)
        self._show_art(track["art"] or None)
        return True  # keep the GLib timer running

    # ── album art ────────────────────────────────────────────────────────
    def _show_art(self, url):
        if url == self._art_url:
            return
        self._art_url = url
        if not url:
            self.art_stack.set_visible_child_name("placeholder")
            return
        if url.startswith("file://"):
            self._set_art(urllib.request.url2pathname(url[len("file://"):]), url)
        elif url.startswith(("http://", "https://")):
            # Fetch off the main loop; Spotify/Firefox hand out https art URLs.
            threading.Thread(target=self._fetch_art, args=(url,),
                             daemon=True).start()
        else:
            self.art_stack.set_visible_child_name("placeholder")

    def _fetch_art(self, url):
        cache = os.path.join(GLib.get_user_cache_dir(), "cc-music")
        os.makedirs(cache, exist_ok=True)
        path = os.path.join(cache, hashlib.sha1(url.encode()).hexdigest())
        try:
            if not os.path.exists(path):
                urllib.request.urlretrieve(url, path)
        except Exception:
            return
        GLib.idle_add(self._set_art, path, url)

    def _set_art(self, path, url):
        if url != self._art_url:   # track changed while we were fetching
            return
        try:
            pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(
                path, ART_SIZE, ART_SIZE, True)
        except Exception:
            self.art_stack.set_visible_child_name("placeholder")
            return
        self.art_image.set_from_pixbuf(pixbuf)
        self.art_stack.set_visible_child_name("art")


def main():
    win = MusicPanel()
    win.connect("destroy", Gtk.main_quit)
    win.show_all()
    Gtk.main()


if __name__ == "__main__":
    main()
